version: "3.9"

services:
  bot:
    container_name: wrss-bot
    build:
      context: .
    image: wrss-bot:${TAG:-latest}
    env_file:
      - /home/.../.../env/bot.env
    restart: unless-stopped
    volumes:
      - ./commands_settings:/app/commands_settings
